export const metadata = {
  title: "Smartie",
  description: "Generated by Next.js",
};
import "primereact/resources/themes/lara-dark-blue/theme.css";
import "tailwindcss/tailwind.css";
import "primereact/resources/primereact.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import "./admin-log/background.css";
import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
